[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# uncomment ONE of these three option to make `cargo run` start a GDB session
# which option to pick depends on your system
# runner = "arm-none-eabi-gdb -q -x openocd.gdb"
#runner = "gdb-multiarch"
# runner = "gdb -q -x openocd.gdb"
#runner = "probe-run --chip STM32F103C8"
#runner = "probe-rs run --chip STM32G431CBUx --probe c251:f001:LU_2022_8888"
#runner = "probe-rs run --chip STM32G431CBUx "


# Terminal
runner = "probe-rs run --chip STM32G431CBUx --probe 0483:3748:39"

# Battery monitor
#runner = "probe-rs run --chip STM32G431CBUx --probe 0483:3748:52C3BF6C0648C2835248756225C287"
#runner = "probe-rs run --chip STM32G431CBUx --connect-under-reset "
#runner = "probe-rs run --chip STM32G431CBUx"

[build]
target = "thumbv7em-none-eabi"    # Cortex-M3

[alias]
rr = "run --release "

[env]
DEFMT_LOG = "trace"

