[package]
name = "stm32f1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bxcan = "0.7.0"
heapless = "0.7.16"
stm32-device-signature = { version = "0.3.3", features = ["stm32f1"] }
