[package]
name = "stm32g4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.16"
#stm32-device-signature = { version = "0.3.3", features = ["stm32g4"] }
